name:                hascurses
version:             0.1.0.0
github:              "github.com/mazhar266/hascurses"
license:             BSD3
author:              "Mazhar Ahmed"
maintainer:          "github.com/mazhar266"
copyright:           "2019 Mazhar Ahmed"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hascurses#readme>

dependencies:
- base >= 4.7 && < 5
- ncurses == 0.2.16
# - c2hs >= 0.15

resolver: lts-2.15

library:
  source-dirs: src

executables:
  hascurses-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hascurses
    - ncurses

tests:
  hascurses-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hascurses
    - ncurses
